name: Generate Snake Animation

on:
  schedule:
    - cron: "0 3 * * *" # Запуск ежедневно в 3 часа ночи
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: dbaglan
          outputs: dist/snake.svg

      - name: Upload the animation
        uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/snake.svg

      - name: Push Snake Animation to Output Branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B output
          mv dist/snake.svg ./
          git add snake.svg
          git commit -m "Generate snake animation"
          git push -f origin output
